import type { Metadata } from 'next';
import { Poppins, Playfair_Display } from 'next/font/google';
import './globals.css';
import ClientWrapper from './components/ClientWrapper';
import { locales } from 'locale.config';


// Font configuration
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-playfair',
});

export const metadata: Metadata = {
  title: 'My Website',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale?: string };
}) {
  // Validate the locale - fall back to 'en' if not valid
  const locale = params?.locale && locales.includes(params.locale) ? params.locale : 'en';

  return (
    <html lang={locale} className="scroll-smooth">
      <body className={`${poppins.variable} ${playfair.variable} font-sans`}>
        <ClientWrapper locale={locale}>
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}